//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvaSAP.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Kayttaja {
            get {
                return ((string)(this["Kayttaja"]));
            }
            set {
                this["Kayttaja"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SapKirjautuminenYhteys {
            get {
                return ((string)(this["SapKirjautuminenYhteys"]));
            }
            set {
                this["SapKirjautuminenYhteys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SapKirjautuminenKirjausjarjestelma {
            get {
                return ((string)(this["SapKirjautuminenKirjausjarjestelma"]));
            }
            set {
                this["SapKirjautuminenKirjausjarjestelma"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SapKirjautuminenKayttaja {
            get {
                return ((string)(this["SapKirjautuminenKayttaja"]));
            }
            set {
                this["SapKirjautuminenKayttaja"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SapKirjautuminenSalasana {
            get {
                return ((string)(this["SapKirjautuminenSalasana"]));
            }
            set {
                this["SapKirjautuminenSalasana"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OpenWorkOrdersFunctionalLocation {
            get {
                return ((string)(this["OpenWorkOrdersFunctionalLocation"]));
            }
            set {
                this["OpenWorkOrdersFunctionalLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Toimintopaikkarajaus {
            get {
                return ((string)(this["Toimintopaikkarajaus"]));
            }
            set {
                this["Toimintopaikkarajaus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Tietokantapolku {
            get {
                return ((string)(this["Tietokantapolku"]));
            }
            set {
                this["Tietokantapolku"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ViimeisinKayttaja {
            get {
                return ((int)(this["ViimeisinKayttaja"]));
            }
            set {
                this["ViimeisinKayttaja"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ViimeisinToimintolaji {
            get {
                return ((string)(this["ViimeisinToimintolaji"]));
            }
            set {
                this["ViimeisinToimintolaji"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AsetuksetAvoimetTyotVariantti {
            get {
                return ((string)(this["AsetuksetAvoimetTyotVariantti"]));
            }
            set {
                this["AsetuksetAvoimetTyotVariantti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Toimipaikka {
            get {
                return ((string)(this["Toimipaikka"]));
            }
            set {
                this["Toimipaikka"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AsetuksetLaitehakuVariantti {
            get {
                return ((string)(this["AsetuksetLaitehakuVariantti"]));
            }
            set {
                this["AsetuksetLaitehakuVariantti"] = value;
            }
        }
    }
}
